#:schema node_modules/wrangler/config-schema.json
name = "sunil-finance"
compatibility_date = "2024-01-01"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sunil"
database_id = "62969f21-d2f6-4254-a37e-9985f779eab1" # The user will replace this with their actual database ID after creating it on Cloudflare
